### PR TITLE
Fix potential Null pointer dereference in regress_dns.c

### PR DESCRIPTION
**Pull request by icy17**

### CODE REVIEW

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
```
[2/3] Building C object CMakeFiles/regress.dir/test/regress_dns.c.o
In file included from /src/le/libevent/test/../log-internal.h:30,
                 from /src/le/libevent/test/../util-internal.h:35,
                 from /src/le/libevent/test/regress_dns.c:27:
/src/le/libevent/test/regress_dns.c: In function ‘test_tcp_resolve’:
/src/le/libevent/include/event2/util.h:152:21: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  152 | #define ev_uint16_t uint16_t
      |                     ^~~~~~~~
/src/le/libevent/test/regress_dns.c:2701:9: note: in expansion of macro ‘ev_uint16_t’
 2701 |         ev_uint16_t portnum = 0;
      |         ^~~~~~~~~~~
/src/le/libevent/test/regress_dns.c: In function ‘test_tcp_resolve_pipeline’:
/src/le/libevent/include/event2/util.h:152:21: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  152 | #define ev_uint16_t uint16_t
      |                     ^~~~~~~~
/src/le/libevent/test/regress_dns.c:2791:9: note: in expansion of macro ‘ev_uint16_t’
 2791 |         ev_uint16_t portnum = 0;
      |         ^~~~~~~~~~~
/src/le/libevent/test/regress_dns.c: In function ‘test_tcp_timeout’:
/src/le/libevent/include/event2/util.h:152:21: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  152 | #define ev_uint16_t uint16_t
      |                     ^~~~~~~~
/src/le/libevent/test/regress_dns.c:2875:9: note: in expansion of macro ‘ev_uint16_t’
 2875 |         ev_uint16_t portnum = 0;
      |         ^~~~~~~~~~~
[3/3] Linking C executable bin/regress
```

**Review by azat — CHANGES_REQUESTED** [review]
.

**Comment by Coeur** [comment]
@azat I'm not clearly seeing how those changes could relate to this build error. Can you try rebasing the branch to top-of-tree, @azat ?

**Comment by azat** [comment]
Merged https://github.com/libevent/libevent/pull/1675 with co-authorship preserved. Thanks!

**Pull request closed without merging**
