### PR TITLE
do not build test programs by default

### PR DESCRIPTION
**Pull request by vapier**
The test binaries are used when you run `make check`, so change the code
so they're only built when you run that target.  It doesn't make sense
to always compile these when you run plain `make`.

### CODE REVIEW

**Comment by azat** [comment]
It's been awhile, and now libevent also support cmake, so we need to either fix both or none. Personally I will prefer not do this at all, since `regress` takes 22 seconds, while `make check` more more longer.
@nmathewson @ellzey ?

**Comment by vapier** [comment]
the issue isn't the execution time, it's the compile time.  test programs should only be compiled & run when explicitly requested.

**Comment by azat** [comment]
> the issue isn't the execution time, it's the compile time.  test programs should only be compiled & run when explicitly requested.

I mean that right now to run regress after some changes you do this:
$ make
$ test/regress

While after you patch you will need do this:
$ make check
^C
$ test/regress

And wait until "make check" finish, which can take awhile, or kill it.
That said that "make check" is not the thing that you must run every
time since it is not light-weight.

But of course you can always do this:
$ make test/regress
$ test/regress

But if you will forget about "make test/regress" and will just run
"make" then you can run stalled regress.

Anyway I don't have any strong objections, and if nobody have them, feel
free to update cmake rules too.

**Comment by vapier** [comment]
yes, you have to build the tool directly.  this is SOP and why the check_XXX target exists in the first place in the automake world.

i see there's already a --disable-libevent-regress flag.  how about we change the default there from enable to disable ?

**Comment by ellzey** [comment]
:+1:

**Comment by ellzey** [comment]
Now that cmake is back in working order, you have this option:

```
-DEVENT__DISABLE_DEBUG_MODE:BOOL=ON
-DEVENT__DISABLE_REGRESS:BOOL=ON
-DEVENT__DISABLE_SAMPLES:BOOL=ON
-DEVENT__DISABLE_TESTS:BOOL=ON
```

This should cover the bases.

**Pull request closed without merging**
