### PR TITLE
expose evhttp_serve to user

### LINKED ISSUE #1471: expose evhttp_get_request to user
can you expose evhttp_get_request to user?

i have a listen thread and some work threads, work threads(IO thread) use evhttp_new  create http server

my listen thread send socket to work threads by load, work thread use evhttp_get_request create http service(i modify it local)

i mainly use libevent for websocket.

thank you!!

### PR DESCRIPTION
**Pull request by Coeur**
Fixes #1471
ALTERNATIVE SOLUTION OF #1683 and #1684.
Cherry-pick of #1685 (only the first two commits).

This PR is aimed at moving forward with the remaining tasks for the 2.2 milestone: https://github.com/libevent/libevent/milestone/4.

This PR is based on @zuiwuchang pull request and exposes evhttp_serve instead of evhttp_get_request.

I did not write a test for it and do not plan to write one myself: I'd like instead those interested in that feature to share a snippet of code that would demonstrate its usage (@zuiwuchang, @azat, ...), and then we could adapt it as a test.

### CODE REVIEW

**Comment by zuiwuchang** [comment]
I'm currently developing on a defective chip, and the asynchronous listener on this platform doesn't work properly, so I can only use a synchronous listener in a separate thread to accept connections and then use evhttp_serve to provide http services.(This is the problem I really need to solve right now https://github.com/powerpuffpenguin/ejs).

In addition, a useful scenario I can envision is to make full use of multi-core CPUs, so create multiple bases and asynchronous listeners, and then use some kind of load balancing algorithm to call evhttp_serve so that http processing can be relatively evenly distributed to different CPUs for processing.

I'll try to take the time to write demo code for the two scenarios above, but I currently have a lot of other code to complete and can't guarantee when the demo will be released. (So it would be great if someone else could post demo code, but if no one keeps posting I'll try to find the time to do this)

**Comment by azat** [comment]
>In addition, a useful scenario I can envision is to make full use of multi-core CPUs, so create multiple bases and asynchronous listeners, and then use some kind of load balancing algorithm to call evhttp_serve so that http processing can be relatively evenly distributed to different CPUs for processing.

Note, that for load balancing you can use SO_REUSEPORT

>I'll try to take the time to write demo code for the two scenarios above

Thanks, looking forward for this.
Don't get me wrong, this new API is simple, but I want to ensure that it will have users, and at least minimal coverage.

**Comment by zuiwuchang** [comment]
> Note, that for load balancing you can use SO_REUSEPORT

SO_REUSEPORT is not supported by some systems such as windows. In addition, not using SO_REUSEPORT but doing load balancing yourself can more flexibly control the load balancing algorithm used.

**Comment by theoden8** [comment]
We use it here also https://github.com/clostra/newnode/blob/1dcdbbc7e8de78e041526a10449367b21fd00398/http.c#L233
Looking forward to this PR

**Comment by theoden8** [comment]
I compressed @zuiwuchang 's example into one file:

https://gist.github.com/theoden8/5135d804c51b2d9da6a3556bc63c70f7

It's about 400LOC. Not all of them are necessarily what this pull request needs.

**Comment by theoden8** [comment]
Also this 91de0161d3fe0ff57db8a0bcd7589af6361058fe would fix #1578 if applied here

**Comment by theoden8** [comment]
@azat 970e9949974c8e944e82282e2d0f774e6ccc47cf
@zuiwuchang mind this rewritten code is included in libevent under BSD-3 clause?

**Review by azat — CHANGES_REQUESTED** [review]
Test is required

**Comment by azat** [comment]
>Also https://github.com/libevent/libevent/commit/91de0161d3fe0ff57db8a0bcd7589af6361058fe would fix https://github.com/libevent/libevent/issues/1578 if applied on top of exposing evhttp_get_request.

@theoden8 let's submit fix on top later, separately

**Comment by Coeur** [comment]
Those interested in the feature should open their own PR. I wrote regarding adding a test for this feature:
>do not plan to write one myself

I'm glad @zuiwuchang and @theoden8 are interested, so please offer a pull request.

**Comment by zuiwuchang** [comment]
> @azat [986efdf](https://github.com/libevent/libevent/commit/986efdfe928f2b887236fce9eb49ce2e37b9adc3) @zuiwuchang mind if this rewritten code is included in libevent under BSD-3 clause?

Nice to see this, i'll like.

**Pull request closed without merging**
