### PR TITLE
android build fix

### PR DESCRIPTION
**Pull request by asmodehn**
A small patch to build libevent on Android, when I thought I would need it.
Hope this can help someone at least.

### CODE REVIEW

**Comment by optedoblivion** [comment]
For android it is common to add the config.h files since autogen doesn't run right under the build env setup.  You have to run . build/envsetup.sh and it doesn't always configure properly.

**Comment by ellzey** [comment]
Now that I've fixed cmake (mostly), can we consider https://github.com/Discordia/android-cmake or something like that?

**Comment by ellzey** [comment]
Also, rebase is your friend.

**Comment by ellzey** [comment]
After reviewing this again. I don't want yet-another-config.in. CMake has been fixed, which generates the config.h's. And projects that assist in cmake + android. Use that.

**Pull request closed without merging**
