### PR TITLE
dns: Return DNS query type on error

### LINKED ISSUE #1219: Propagate back the DNS resolution error to the user
This is related to this issue found in tor: https://gitlab.torproject.org/tpo/core/tor/-/issues/40490

Basically, in the user callback, when a DNS resolution error occurs, the DNS query type is always 0. This turned out problematic for us because we keep stats on which DNS query type fails and for what reasons.

The code is in `reply_run_callback()` where on error, the type is always 0:

`cb->user_callback(cb->err, 0, 0, cb->ttl, NULL, user_pointer);`

Maybe there is an historical or technical reason for this, I'm not sure but seems an easy fix. Merge request coming up in a bit.

### PR DESCRIPTION
**Pull request by dgoulet-tor**
When calling the user callback after a DNS resolution on error, make
sure to send back the query type (A, AAAA, PTR).

Closes #1219

Signed-off-by: David Goulet <dgoulet@torproject.org>

### CODE REVIEW

**Review by azat — DISMISSED** [review]
LGTM. Can you also add a simple unit test into test/regress_dns.c?

**Comment by dgoulet-tor** [comment]
So I've fixed the test suit issue _but_ here locally, I get another error that I can't figure out.

```
  FAIL test/regress_dns.c:2275: assert(gaic_freed != 1000): 1000 vs 1000
dns/getaddrinfo_cancel_stress: [msg] Nameserver 127.0.0.1:37537 has failed: request timed out.
```

Now, another thing I noticed. I had to modify couple unit tests that were explicitly expecting to **not** have the right type on error. And so that made me think, with this patch, how likely it is that we'll break a whole lot of projects that had assumed the same?

**Comment by ploxiln** [comment]
> how likely it is that we'll break a whole lot of projects

I think it's _unlikely_, most would probably check that `result != DNS_ERR_NONE` and then ignore type because it was useless. But it is theoretically possible that some application using libevent/evdns looked for `type == 0` to check for error ... it might be appropriate to try to search github for all users of evdns, or wait for a libevent-2.2 release for this kind of change ...

**Comment by azat** [comment]
>Now, another thing I noticed. I had to modify couple unit tests that were explicitly expecting to not have the right type on error. 

@dgoulet-tor I don't see it. Is this in our CI? Can you give a link? Anyway this does not looks related to this patch set.

> And so that made me think, with this patch, how likely it is that we'll break a whole lot of projects that had assumed the same?

I think it is OK to change this part of the interface, but if you doubt, we can do this under flag (for `evdns_base_new`)

>or wait for a libevent-2.2 release for this kind of change ...

@ploxiln It will not be backported anyway.

**Review by azat — APPROVED** [review]

**Pull request merged**
