### PR TITLE
bufferevent: make sure we can call bufferevent_priority_set

### PR DESCRIPTION
**Pull request by nicboul**
on bufferevent of type ssl too.

### CODE REVIEW

**Comment by azat** [comment]
>libevent:patches-2.1

The target branch should be master, it just need to be backported to the 2.1 after

**Comment by nicboul** [comment]
The way the code is designed, it's not possible to call this macro right now:

```
@@ -661,7 +661,7 @@ bufferevent_priority_set(struct bufferevent *bufev, int priority)
        struct bufferevent_private *bufev_p = BEV_UPCAST(bufev);

        BEV_LOCK(bufev);
-       if (!BEV_IS_SOCKET(bufev))
+       if (!BEV_IS_SOCKET(bufev) || !BEV_IS_OPENSSL(bufev))
                goto done;

        if (event_priority_set(&bufev->ev_read, priority) == -1)
vagrant@stretch:~/libevent$ make
make  all-am
make[1]: Entering directory '/home/vagrant/libevent'
  CCLD     sample/dns-example
./.libs/libevent.so: undefined reference to `bufferevent_ops_openssl'
```
Do you have any suggestion ?

**Comment by azat** [comment]
>./.libs/libevent.so: undefined reference to `bufferevent_ops_openssl'

This is because it is in another library (libevent_openssl.so)

>Do you have any suggestion ?

Ok, let's leave just `if (BEV_IS_ASYNC(bev) || BEV_IS_FILTER(bev) || BEV_IS_PAIR(bev)) goto done;`

**Comment by nicboul** [comment]
Ok thanks, will create a PR against the master branch

**Pull request closed without merging**
