### PR TITLE
Add support for EV_TIMEOUT to event_base_active_by_fd

### PR DESCRIPTION
**Pull request by JohnOhl**
Support for EV_TIMEOUT was removed from event_base_active_by_fd back in 87fa2b004a65257a6cba4b57dc7fc0fb06106342. This adds it back. 

Let me know if anything seems amiss, thanks!

### CODE REVIEW

**Comment by ellzey** [comment]
Can you add unit tests?

**Comment by JohnOhl** [comment]
Sure, I'll see what I can put together!

**Comment by JohnOhl** [comment]
Added test, any thoughts? Thanks!!

**Comment by ellzey** [comment]
:+1: @azat ?

**Comment by azat** [comment]
> :+1: @azat ?

@ellzey, @JohnOhl

I looked through this a while ago, and AFAIR I didn't like the
copy-paste this patch has, can we reduce it?

Also we have event_base_foreach_event(), can we [re-]implement
event_activate_by_fd() using it?

**Comment by azat** [comment]
> Also we have event_base_foreach_event(), can we [re-]implement
event_activate_by_fd() using it?

We don't have any existing helper, will be addressed later

@JohnOhl sorry for the enormous delay, applied (squashed and rebased a little), thanks!

**Pull request closed without merging**
