### PR TITLE
miscellaneous autotools related improvements.

### PR DESCRIPTION
**Pull request by fanquake**
An effort to somewhat modernize the autotools usage here (with a minimum required autotools of 2.67 in mind). This removes calls to obsolescent macros, such as `AC_PROG_GCC_TRADITIONAL`, updates macro usage, in the case of `AC_OUTPUT`,  and generally tries to make `configure.ac` more readable and consistent. It also removes the `NTP_PKG_CONFIG` macro in favour of calling `PKG_PROG_PKG_CONFIG`.

I have some more changes done, but decided to PR these as a start. Happy to split this PR up if needed.

### CODE REVIEW

**Comment by azat** [comment]
>[mingw / autotools (none) (pull_request) Failing after 2m — autotools (none)](https://github.com/libevent/libevent/pull/1171/checks?check_run_id=2846529259)

```
../configure: line 14103: syntax error near unexpected token `0.15.0'
../configure: line 14103: `PKG_PROG_PKG_CONFIG(0.15.0)'
```

Can you take a look?

**Review by azat — DISMISSED** [review]

**Comment by azat** [comment]
Also maybe there is a better fix for mingw build then 72138063466067b2b5c27d81e18bca0e3b610591 ?

**Comment by fanquake** [comment]
> Can you take a look?

Is it possible there is a caching or similar issue here? I cannot recreate this when cross compiling on a Ubuntu box. i.e `./autogen.sh && ./configure --host=x86_64-w64-mingw32`.

> Also maybe there is a better fix for mingw build then 7213806 ?

Happy to look at this as well.

**Comment by azat** [comment]
>Is it possible there is a caching or similar issue here?

BTW if you think that this is a caching issue (which is unlikely, but still), you can try changing the cache key here - https://github.com/libevent/libevent/blob/73ca1801885922c49a39643bb56b3abd0e4f8ca9/.github/workflows/mingw.yml#L42

**Comment by fanquake** [comment]
Issues here should be resolved. Looks like the problem was that `pkg-config` wasn't actually installed in the mingw-w64 CI.

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
>Issues here should be resolved. Looks like the problem was that pkg-config wasn't actually installed in the mingw-w64 CI.

Thanks!

**Comment by azat** [comment]
@fanquake it, likely, breaks one of builds:

```
Step #4: ./configure: line 13438: syntax error near unexpected token `0.15.0'
Step #4: ./configure: line 13438: `PKG_PROG_PKG_CONFIG(0.15.0)'
```

- autoconf 2.69-9
- autotools-dev 20150820.1
- automake 1:1.15-4ubuntu1

Can you take a look?

**Comment by fanquake** [comment]
> Can you take a look?

That issue is due to `pkg-config` not being installed. Are you seeing this in the CI, or building locally?

**Comment by azat** [comment]
Right, thank you! The issue pops up in the oss-fuzz builds - https://github.com/google/oss-fuzz/pull/6032
Maybe we can put a check that will give understandable message?

**Comment by fanquake** [comment]
> Maybe we can put a check that will give understandable message?

Sure. See #1182.

**Pull request merged**
