### PR TITLE
tests: fix macOS CI runs

### PR DESCRIPTION
**Pull request by ploxiln**
hopefully...

### CODE REVIEW

**Comment by ploxiln** [comment]
The regress_http macOS build failure is due to this old-but-recently-committed commit: f446229b2206691eae7ec892e68b2a0d6ef61306

That also seems to be what caused the windows failures (but I'm not sure I'll dig into those):

```
http/parse_uri_un: 
  FAIL D:\a\libevent\libevent\test\regress_http.c:3041: Couldn't parse unix socket URI "http://unix:a:"
  [parse_uri_un FAILED]
http/parse_uri_un_nc: 
  FAIL D:\a\libevent\libevent\test\regress_http.c:3041: Couldn't parse unix socket URI "http://unix:a:"
  [parse_uri_un_nc FAILED]
[msg] Nameserver 127.0.0.1:52955 has failed: request timed out.
[msg] All nameservers have failed
[warn] EVDNS_SOPT_TCP_MAX_CLIENTS option can be set only on TCP server
[warn] EVDNS_SOPT_TCP_MAX_CLIENTS option can be set only on TCP server
[warn] EVDNS_SOPT_TCP_IDLE_TIMEOUT option can be set only on TCP server
[warn] EVDNS_SOPT_TCP_IDLE_TIMEOUT option can be set only on TCP server
2/407 TESTS FAILED. (57 skipped)
```

**Comment by ploxiln** [comment]
(I'll squash these commits, and remove the 2 wepoll test skips which seem to not work)

**Comment by ploxiln** [comment]
two consistent windows/mingw failures remain, when using WEPOLL:

```
 2/419 TESTS FAILED. (51 skipped)
FAILED
 regress_debug: http/data_length_constraints: 
  FAIL ../test/regress_http.c:4589: assert(req)
  [data_length_constraints FAILED]

  http/max_connections: 
  FAIL ../test/regress_http.c:5241: assert(state->connections_throttled >= state->connections_error): 0 vs 1
  FAIL ../test/regress_http.c:5252: (Failed.)
  [max_connections FAILED]
```

I'll leave those for someone to fix separately :)

**Comment by ploxiln** [comment]
also, this seems to intermittently fail on linux:

```
 44/54 Test #51: test-ratelim__group_lim .....................   Passed    5.31 sec
45/54 Test #50: regress__POLL_debug .........................   Passed   89.64 sec
46/54 Test #40: regress__SELECT_debug .......................***Failed   90.28 sec
http/unix_socket: 
  FAIL .../libevent/test/regress_http.c:2279: assert(!evhttp_bind_unixsocket(myhttp, "foo"))
  [unix_socket FAILED]
```

and this seems to intermittently fail on macOS? or maybe just for some configurations?

```
  test-dumpevents: OKAY
 regress: [Lost connection!] 
  [simplestsignal FAILED]
[warn] ...
1/418 TESTS FAILED. (49 skipped)
FAILED
[warn] ...
 regress_debug: OKAY
```

I also do not plan to not address these in this PR

**Review by azat — APPROVED** [review]
Many thanks!

**Pull request merged**
