### PR TITLE
Bufferevent filter data stuck input underlying fix v1

### PR DESCRIPTION
**Pull request by EMPanisset**
Providing fix and regression test case as requested.

### CODE REVIEW

**Comment by azat** [comment]
Refs #362

**Comment by azat** [comment]
@EMPanisset thanks for unit test and patch, rebased a little bit:
    `git@github.com:azat/libevent.git be-filter-data-stuck` (are you okay with this?)

And applied.

Regards,
Azat.

**Comment by EMPanisset** [comment]
Hi Azat,

Thank you for applying that. I am okay with rebase, no problem.

Regards,
Eduardo Panisset.

**Comment by azat** [comment]
@EMPanisset thanks! Upstream hash is 9b294082fb597ba3e1f90f0b4cfb83b4c56fe059

**Pull request closed without merging**
