### PR TITLE
Forgot to install OpenSSL for appveyor

### PR DESCRIPTION
**Pull request by JoakimSoderberg**

### CODE REVIEW

**Comment by JoakimSoderberg** [comment]
Ah yes, building works in this repo at least! But you should still signup using your other @nmathewson account as well.

Some of the regression tests fail. I'm not sure if that's a bug or unreliable tests. Might be good to turn them off if they're not reliable?

**Comment by JoakimSoderberg** [comment]
Fails on Windows. But not due to my changes:

```
http/data_length_constraints: [forking] 
[msg] libevent using: win32
  FAIL ..\test\regress_http.c:3591: assert(req)
  FAIL ..\test\regress_http.c:3600: assert(req)
  [data_length_constraints FAILED]
[msg] libevent using: win32
```

https://github.com/libevent/libevent/blob/master/test/regress_http.c#L3591
https://github.com/libevent/libevent/blob/master/test/regress_http.c#L3600

**Comment by nmathewson** [comment]
Thanks; will investigate once I have time.  (At work now; likely to be v tired later)

**Comment by ellzey** [comment]
> Fails on Windows. But not due to my changes:
 
weird path, resulting in the callback request argument being NULL (already freed)

Investigating.

**Pull request merged**
