### PR TITLE
Improve support for CloudABI.

### PR DESCRIPTION
**Pull request by EdSchouten**
Nuxi CloudABI is a secure UNIX-like runtime environment, based on the principles of capability-based security. The C library used by CloudABI (cloudlibc) implements a large part of POSIX, except for the features that don't make sense in a pure capability system.

This pull request performs a couple of basic cleanups to the source code to make libevent build more cleanly on this system.

### CODE REVIEW

**Comment by azat** [comment]
```evutil_secure_rng_add_bytes()``` (4c00fe3) - this one we can't just simply merge since it exported, but since there is no 2.1 stable, maybe we could pick this for 2.1 stable? Need some time to think about this.

**Comment by azat** [comment]
Also the patch with ```EVFILT_SIGNAL``` does have a lot of #ifdef (9fbcf4f), and also for ```event_disable_debug_mode()``` (4a2708d) we already have #271 and #224.

**Comment by azat** [comment]
- a893f48b40d92ea6e959110319b4ee933428eef3 -- applied
- 31f211221461964df574c2da647e286bb581397a -- applied (indeed fixes freebsd build)
- 823e1abf53a29a6c98045241ae90c6cae3144ce3 -- applied
- 4a2708da20f186e5b183a1dedf4c8deb34d64ae3 -- see bfcedee0385cdb0b5f6ed063075a664d513b342e

Other patches need some changes. Will it be okay if I will close this, and you will open new pr for new patches?

Thanks for you work!

**Comment by EdSchouten** [comment]
Hi Azat,

Thanks for integrating some of these fixes already. Really appreciate it! Regarding `evutil_secure_rng_add_bytes()`: Sure! Removing this function in a future version of the library would be nice. Maybe we should add some kind of marker to the function to indicate that it's (going to be) deprecated?

Regarding `EVFILT_SIGNAL`: CloudABI simply doesn't have any signal handling support at all (which seems to work out nicely, by the way). This is the reason why it doesn't have `EVFILT_SIGNAL`, but does support the other filters. I do realize that CloudABI is a bit of an odd duck in that sense. If you know of a cleaner way to solve this without making a mess out of the code, be sure to let me know how and I will implement it.

It is all right if you close this pull request. I'll create a new pull request in the nearby future with some cleaned up patches.

Thanks,
Ed

**Pull request closed without merging**
