### PR TITLE
Increase Travis' $TIMEOUT so cmake doesn't fail

### PR DESCRIPTION
**Pull request by pprindeville**
See if we can get a successful build under load by doubling $TIMEOUT.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by azat** [comment]
> See if we can get a successful build under load by doubling $TIMEOUT.

Like I wrote in #644 I don't see that $TIMEOUT is too small.
How did you come into this conclusion?

**Comment by pprindeville** [comment]
Still seeing:

```
The command cmake --build . --target verify exited with 2.
```

though not with any context showing why it's failing.

**Comment by pprindeville** [comment]
> How did you come into this conclusion?

You said that if the VM is on a machine under heavy load, then things can take longer.  I was testing that theory.

**Comment by pprindeville** [comment]
Also, do we know why these tests are failing?

```
The following tests FAILED:
	  8 - regress__timerfd_EPOLL (Failed)
	  9 - regress__timerfd_EPOLL_debug (Failed)
	 17 - regress__changelist_EPOLL (Failed)
	 18 - regress__changelist_EPOLL_debug (Failed)
	 26 - regress__timerfd_changelist_EPOLL (Failed)
	 27 - regress__timerfd_changelist_EPOLL_debug (Failed)
	 35 - regress__SELECT (Failed)
	 36 - regress__SELECT_debug (Failed)
	 44 - regress__POLL (Failed)
	 45 - regress__POLL_debug (Failed)
Errors while running CTest
```

**Comment by pprindeville** [comment]
Closing as this reduces some of the failures but doesn't eliminate them so the problem seems to lie elsewhere.

**Pull request closed without merging**
