### PR TITLE
Implement size limits on HTTP header number.

### PR DESCRIPTION
**Pull request by dennis-zheng**

### CODE REVIEW

**Comment by dennis-zheng** [comment]
I implemented measures to prevent a slow HTTP attack caused by an excessive number of HTTP headers.
Additionally, I have conducted tests in regress_http.c.
regress _http_data_length_constraints

**Review by azat — APPROVED** [review]
LGTM. Will you use this new API in your code?

**Comment by azat** [comment]
CI failed:

```
/home/runner/work/libevent/libevent/test/regress_http.c:4849:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 4849 |  char header_index[NI_MAXSERV];
      |  ^~~~
/home/runner/work/libevent/libevent/test/regress_http.c:4850:20: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘const long unsigned int’} [-Werror=sign-compare]
 4850 |  for (int i = 0; i < size; ++i) {
      |                    ^

```

**Comment by azat** [comment]
CI still in a bad state, rebased on top of master

**Comment by azat** [comment]
Newly added test fails - https://github.com/libevent/libevent/actions/runs/10990630000/job/30511257149?pr=1577:

```
[Lost connection!] 
  [RETRYING http/data_length_constraints (attempts left 2, delay 1 sec)]
[Lost connection!] 
  [RETRYING http/data_length_constraints (attempts left 1, delay 1 sec)]
[Lost connection!] 
  [RETRYING http/data_length_constraints (attempts left 0, delay 1 sec)]
[Lost connection!] 
```

**Pull request closed without merging**
