### PR TITLE
Don't loose top error in SSL

### PR DESCRIPTION
**Pull request by NeitrinoK**

### CODE REVIEW

**Comment by NeitrinoK** [comment]
@azat Hi what difference between AppVeyor with 2.2.0.637 and 2.2.0.52
https://ci.appveyor.com/project/libevent/libevent/builds/22652448/job/97it2737yetfu836
and
https://ci.appveyor.com/project/nmathewson/libevent
I can't find how my code can break tests in such way

**Comment by azat** [comment]
@NeitrinoK it is not you, it is flackiness of tests that uses time difference

**Comment by azat** [comment]
Egh, there are two CI projects enabled in the appveyor, I've just disabled the one that in `nmathewson` namespace

**Comment by azat** [comment]
Applied, thanks!

**Pull request closed without merging**
