### PR TITLE
Add CI checks for OpenBSD

### PR DESCRIPTION
**Pull request by Neilpang**
Support 6.9 and 7.1

Refs: #1316

### CODE REVIEW

**Comment by azat** [comment]
netbsd 6.9 fails because of this:

```
2022-08-17T04:59:58.8339420Z libtool: link: (cd ".libs" && rm -f "libevent.so.1.0" && ln -s "libevent-2.2.so.1.0" "libevent.so.1.0")
```

And this is wrong, it should be:

```
libtool: link: (cd ".libs" && rm -f "libevent-2.2.so.1" && ln -s "libevent-2.2.so.1.0.0" "libevent-2.2.so.1")
libtool: link: (cd ".libs" && rm -f "libevent.so" && ln -s "libevent-2.2.so.1.0.0" "libevent.so")
```

And I think that 7.1 should also fail, however it has system-wide libevent installed with evdns in the libevent.so

**Comment by azat** [comment]
>[build / openbsd-cmake-job (7.1, TEST_EXPORT_SHARED) (pull_request) Failing after 11m](https://github.com/libevent/libevent/actions/runs/3040157553/jobs/4895892812)

```
...
2022-09-13T06:38:29.2150790Z [test-export] test for install tree(in system-wide path)
2022-09-13T06:38:29.2151500Z [test-export] fail: link core and run core expects success but gets failure.
2022-09-13T06:38:29.2063870Z /usr/bin/cc CMakeFiles/test-export.dir/test-export.c.o -o test-export   -L/usr/local/lib  -Wl,-z,origin,-rpath,/usr/local/lib -levent_core-2.2 -lpthread -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib 
2022-09-13T06:38:29.2152190Z ld: error: unable to find library -levent_core-2.2
```

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
@Neilpang thank you! I've disabled 6.9 for now and also I have to disable `TEST_EXPORT_SHARED` too. But apart from this everything is good!

**Comment by Neilpang** [comment]
I see, thank you.

**Comment by azat** [comment]
FYI I disabled them https://github.com/libevent/libevent/commit/b9e1fe74e724a3f1524904b4658b9a4acdea50f5 due to lack of runners

**Pull request merged**
