### PR TITLE
fix and enable load_nameservers_from_registry() fallback

### PR DESCRIPTION
**Pull request by mfriedl**
evdns_nameserver_ip_add_line() should return an error if an empty string is passed, so load_nameservers_from_registry() gets called if load_nameservers_with_getnetworkparams() cannot find any nameserver.

load_nameservers_from_registry() needs to:

- iterate over interfaces
- check for STATUS_SUCESS when fetching the size of the registry entry
- use ascii variant of the lookup function since result is used as a string
- null-terminate the retrieved registry value
- release key handles on error

### CODE REVIEW

**Review by azat — COMMENTED** [review]
Thank you! Is it possible to write a test?

**Comment by mfriedl** [comment]
I have not checked yet, as this function is not public to the outside. Am 03.03.2024 um 14:14 schrieb Azat Khuzhin ***@***.***>:﻿
@azat commented on this pull request.

Thank you! Is it possible to write a test?

**Comment by azat** [comment]
It can be exposed via private header (`evdns-internal.h`), though I was talking about testing it as part of a regular NSes load, but I guess to test it you need to change windows registry?

**Comment by azat** [comment]
@mfriedl will you continue working on this?

**Comment by azat** [comment]
@mfriedl I will close this one since there are lots of conflicts anyway, feel free to resubmit!

**Pull request closed without merging**
