### PR TITLE
[Windows CI] Fix failing mingw build tasks.

### PR DESCRIPTION
**Pull request by rectified95**
I found the correct path by looking at the _Disable Key Refresh_ step in _mingw::autotools::set up msys2_ task (https://github.com/rectified95/libevent/runs/5858227589?check_suite_focus=true)

_C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe "((Get-Content -path **D:\a\_temp\msys64**\etc\post-install\07-pacman-key.post -Raw) ..._

### CODE REVIEW

**Comment by rectified95** [comment]
If this works out here like it did locally for me, then this PR can be closed: https://github.com/libevent/libevent/pull/1258

**Comment by rectified95** [comment]
@azat Please trigger the CI run :) 
Along with https://github.com/libevent/libevent/pull/1266 this will bring the Windows CI to a building state and restore its regression detecting capability. (I've already spotted some _wepoll_ test failing in my fork)

**Comment by rectified95** [comment]
This PR was supposed to fix the _build_ stage of the `mingw` task, and it seems to have worked. The failures are at the test stage now, but those are regressions introduced why the pipeline was broken, not due to this check-in.

**Comment by azat** [comment]
>This PR was supposed to fix the build stage of the mingw task, and it seems to have worked. The failures are at the test stage now, but those are regressions introduced why the pipeline was broken, not due to this check-in.

Indeed, many thanks! Applied.

BTW maybe you can also take a look/have ideas at why [wepoll does not passes](https://github.com/libevent/libevent/runs/5861843355?check_suite_focus=true)?


```
      Start 10: regress__WEPOLL_debug
10/24 Test #10: regress__WEPOLL_debug ...............Exit code 0xc0000135
***Exception:   0.01 sec
```

*P.S. I'm not a windows user*

**Comment by rectified95** [comment]
Thanks for merging and being so responsive! I'm interested to know why the test is failing too. I can a take quick look but want to first focus on making the new backend pass all analogous tests before fixing _wepoll_.

**Pull request merged**
