### PR TITLE
Reuse connected address on retry

### PR DESCRIPTION
**Pull request by azat**
This patchset will reduce number of requests to nameservers.

### CODE REVIEW

**Comment by azat** [comment]
On Mon, Dec 15, 2014 at 01:59:43PM -0800, John Ohl wrote:
> I'm in favor of this type of feature, although just a thought, should we have a flag or optional toggle to disable or enable the caching? Could this cause adverse behavior if someone were expecting it (or wanted it) to re-query the DNS server between attempts? For example, endpoints that use DNS for failover or those that have short TTLs, etc where the endpoint could change between retries.

Hi John,

As I promised -- here is updated patchset with
evhttp_connection_set_flags(con, EVHTTP_CON_REUSE_CONNECTED_ADDR) API.
[ For now I don't sure is it ok to use evcon->flags for this purpose,
but I don't see any disadvantages of this method, except for mess with
half of flags in http-internal.h and other half in http.h ]

https://github.com/azat/libevent/compare/libevent:master...azat:reuse-conn_address-on-retry-v10?expand=1

Cheers,
Azat.

**Comment by nmathewson** [comment]
Another review, one quick request:
  * I would be more comfortable if bufferevent_socket_set_conn_address made sure that addrlen was not too big.
  * In be_socket_destruct, can conn_address be NULL?  We should probably check for NULL before passing it to mm_free(). 
  * evutil_sockaddr_port_ needs documentation.
  * I'm not seeing the REUSE_CONNECTED_ADDR code; is that somewhere different? Am I looking in the wrong place?
  * The new functions in bufferevent_sock.c need documentation.

**Comment by nmathewson** [comment]
oh wait, you wanted me to look at the v10 branch.  hang on...

**Comment by azat** [comment]
v10
https://github.com/libevent/libevent/compare/master...azat:reuse-conn_address-on-retry-v10

**Comment by azat** [comment]
Merged https://github.com/libevent/libevent/compare/master...azat:reuse-conn_address-on-retry-v11

**Pull request closed without merging**
