### PR TITLE
Return from 'event_del()' after the last event callback termination

### PR DESCRIPTION
**Pull request by jmillan**
Delete the event from the queue before blocking for the current
event callback termination.

Provides a mechanism to securely access data which is
handled in the event callack.

### CODE REVIEW

**Comment by jmillan** [comment]
This PR is related to issue #225

**Comment by azat** [comment]
Looks good to me (for `EV_SIGNAL` too).
But firstly you should rebase it on top of master (because of 8eedeabe5), otherwise it is unmergeble (though this conflict is pretty easy to fix).

@nmathewson could you take a look?

**Comment by jmillan** [comment]
Hi,

#236 PR has been made to accommodate the patch to master branch.

The patch was originally made for  `release-2.0.21-stable`, which I use in production and the issue is fixed.

**Comment by jmillan** [comment]
Hi @azat,

Has the PR simply been discarded? I cannot see any related commit in master branch.

**Comment by azat** [comment]
Hi,

Yep, since we have #236, am I missing something?

**Comment by jmillan** [comment]
No, you're not missing anything. It was me; I thought the issue had been invalidated.

**Pull request closed without merging**
