### PR TITLE
libevent_core and libevent_extra also deserve a pkgconfig file

### PR DESCRIPTION
**Pull request by heyleke**

### CODE REVIEW

**Comment by heyleke** [comment]
I don't see what my changes have to do with the AppVeyor build failure, but I never used AppVeyor, so it could be me?

**Comment by azat** [comment]
On Tue, Apr 19, 2016 at 11:35:07PM -0700, Jan Heylen wrote:
> I don't see what my changes have to do with the AppVeyor build failure, but I never used AppVeyor, so it could be me?

Nope, don't think about this, your patches doesn't break appveyor (this
is just tests that must be fixed, to avoid false-positive).

**Comment by ellzey** [comment]
mergealicious??

**Comment by ellzey** [comment]
Once merged, I will make it cmake'ified too

**Comment by azat** [comment]
Yep every thing is fine (including deb package), @heyleke thanks!
@ellzey go ahead!

**Comment by heyleke** [comment]
I actually need this on the 2.0.x branch, is there going to be a 2.0.23 one day containing this? Or do I submit a pull request for the patches-2.0 branch too?

**Comment by azat** [comment]
Refs: #351

**Pull request merged**
