### PR TITLE
README simplification

### PR DESCRIPTION
**Pull request by sntdevco**
Round 1 of README simplification

### CODE REVIEW

**Comment by sntdevco** [comment]
@azat All set to roll

**Comment by azat** [comment]
>now looking onto Documentation

Are you going to do this separately/later?

**Comment by sntdevco** [comment]
> Are you going to do this separately/later?

Yeah, I'll be pushing that separately, you can merge this for now

**Comment by azat** [comment]
From https://github.com/libevent/libevent/pull/785#issuecomment-470625973
> I don't think that it is useful to put add/delete of the contributors into separate commits, can you squash them? (only two, not three)

I rebased your patches a little (56c9551), objections?

**Comment by sntdevco** [comment]
> From [#785 (comment)](https://github.com/libevent/libevent/pull/785#issuecomment-470625973)
> 
> > I don't think that it is useful to put add/delete of the contributors into separate commits, can you squash them? (only two, not three)
> 
> I rebased your patches a little ([56c9551](https://github.com/libevent/libevent/commit/56c9551e2dea27a2c6fd1e2374968a9f8086b631)), objections?

Nope, go ahead

**Comment by azat** [comment]
Applied, thanks!

**Comment by sntdevco** [comment]
@azat Come on Gitter and we'll discuss the Documentation, I'm free on Saturday and Sunday and I'll do this work, it'd be easier if I could directly push code into your repo and we'd have RFCs but never mind, let's do this

**Comment by azat** [comment]
> Come on Gitter and we'll discuss the Documentation

I will be there once I will receive notification from gitter

**Pull request closed without merging**
