### PR TITLE
Initialize variable to 0 replace use memset function in sample/hello-world.c

### PR DESCRIPTION
**Pull request by iysheng**
Initialize a zeros variable when defined, replace using memset function.

### CODE REVIEW

**Comment by iysheng** [comment]
> Can you please change the subject to:
> 
>     * add `sample/hello-world`
> 
>     * fit commit subject to 80 chars
I've changed the subject title, and do I need to modify the commit message and then resubmit a pr?

**Comment by ygj6** [comment]
Initializing to zero implies `memset`.  Why do want such? For performance reasons？

**Comment by iysheng** [comment]
Yeah, and initialization when defining a variable is a good guideline, unless you know exactly that you will quickly initialize the variable explicitly.

> Initializing to zero implies `memset`. Why do want such? For performance reasons？

Yeah, and initialization when defining a variable is a good guideline, unless you know exactly that you will quickly initialize the variable explicitly.

**Comment by azat** [comment]
>I've changed the subject title, and do I need to modify the commit message and then resubmit a pr?

I don't see, but all you need to do is `git commit --amend` and then force push

**Comment by iysheng** [comment]
> > I've changed the subject title, and do I need to modify the commit message and then resubmit a pr?
> 
> I don't see, but all you need to do is `git commit --amend` and then force push

Okay, I've modified the commit message and force push.

**Pull request merged**
