### PR TITLE
Fix build with LibreSSL 2.7

### PR DESCRIPTION
**Pull request by Sp1l**
LibreSSL 2.7 implements OpenSSL 1.1 API

See also: https://bugs.freebsd.org/226900
Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>

### CODE REVIEW

**Comment by azat** [comment]
Hi, thank you for the patches, but I couldn't compile them with libressl-portable/portable@d34dced am I missing something?

It reports that there is no such funtion `BIO_get_init(b)`, and indeed libressl from that location doesn't have it

**Comment by Sp1l** [comment]
Hi Azat, the libressl-portable/portable repo isn't a buildable LibreSSL (without performing the release-mgr tasks to generate). You'll have to get the tarball via https://libressl.org.

My patch is incomplete... LibreSSL 2.7 implements _most of_ the OpenSSL 1.1 API but not _all_ of it. Let me fix that and add to the pull-request. The patch in https://bugs.freebsd.org/226900 is functional, I shouldn't have tried to redo that...

**Comment by azat** [comment]
Maybe you know about any plans on adding `BIO_get_init` by libressl?

**Comment by azat** [comment]
> Hi Azat, the libressl-portable/portable repo isn't a buildable LibreSSL (without performing the release-mgr tasks to generate). You'll have to get the tarball via https://libressl.org.

That's a pity (anyway my build from git seems to work after running `autogen.sh` of course)

> My patch is incomplete... LibreSSL 2.7 implements most of the OpenSSL 1.1 API but not all of it. Let me fix that and add to the pull-request. The patch in https://bugs.freebsd.org/226900 is functional, I shouldn't have tried to redo that...

Okay, it works now. Thanks for fixing this quickly.

**Comment by azat** [comment]
Applied, thanks again!

**Comment by ploxiln** [comment]
@azat this patch 28b8075400c70b2d2da2ce07e590c2ec6d11783d may also be appropriate for backporting for the 2.1.9 release, I currently apply it (after d057c45) to my 2.1.8 build

**Comment by azat** [comment]
Thanks, queued!

**Pull request closed without merging**
