### PR TITLE
windows socketpair tmpfile: use random prefix

### LINKED ISSUE #1058: Make create_tmpfile more durable in Windows
This is the current implementation of `create_tmpfile` in Windows, this implementation can into collisions and thus lead to a failed initialization in `event_base_new`

``` C++
static int
create_tmpfile(char tmpfile[MAX_PATH])
{
	char short_path[MAX_PATH] = {0};
	char long_path[MAX_PATH] = {0};
	char *tmp_file = tmpfile;

	GetTempPathA(MAX_PATH, short_path);
	GetLongPathNameA(short_path, long_path, MAX_PATH);
	if (!GetTempFileNameA(long_path, NULL, 0, tmp_file)) {
		event_warnx("GetTempFileName failed: %d", EVUTIL_SOCKET_ERROR());
		return -1;
	}
	return 0;
}
```

According to the documentation of msdn:

> Due to the algorithm used to generate file names, GetTempFileName can perform poorly when creating a large number of files with the same prefix. In such cases, it is recommended that you construct unique file names based on GUIDs.

Also this leads to an upper limit and competition in the number of temp files that we can generate since we compete with all the other process that create temp files with the default (`NULL`) prefix.

My approach would be to create a GUID and take the first 8-10 chars and use them as the prefix. This will increase the entropy sufficiently and make the function more durable. Any other approaches are also welcomed.

If you are accepting patches and you can give me a code review I can push a PR for it.

### PR DESCRIPTION
**Pull request by ploxiln**
fixes #1058

GetTempFileNameA() takes an optional prefix, and a "unique" long value
which can optionally be zero, which causes it to automatically
increment until a not-yet-existing filename is found.

When libevent creates many AF_UNIX socketpairs on windows,
it slows down dramatically, due to always using the same blank prefix,
and GetTempFileNameA() needing to iterate through all the existing
socketpair filenames. With a present and varying prefix, it will have
much less need to iterate.

It was also possible for a race with other processes also using
blank-prefix tmpfile names to result in both trying to start using
the same name at the same time (because libevent deletes the file
and then re-creates it as a unix socket), which should now be
much less likely.

Unfortuantely, "much" is just a factor of 32k, because the prefix
is only 3 characters, and windows filesystems are case-insensitive,
so doing better would require more sophisticated windows API usage
and charset trickyness.

-----

I'm depending completely on the CI for build and test, because I don't have a windows system with an appropriate build toolchain setup, I normally work on Linux and macOS ... and just found this kinda interesting I guess.

For reference:

```
UINT GetTempFileNameA(
  LPCSTR lpPathName,
  LPCSTR lpPrefixString,
  UINT   uUnique,
  LPSTR  lpTempFileName
);
```

> lpPrefixString: The null-terminated prefix string. The function uses up to the first three characters of this string as the prefix of the file name. This string must consist of characters in the OEM-defined character set.

> If uUnique is zero, the function attempts to form a unique file name using the current system time. If the file already exists, the number is increased by one and the functions tests if this file already exists. This continues until a unique filename is found; the function creates a file by that name and closes it. Note that the function does not attempt to verify the uniqueness of the file name when uUnique is nonzero.

### CODE REVIEW

**Comment by ploxiln** [comment]
Silly separate  test:

```c
#include <stdio.h>

#include <event2/util.h>

int main()
{
	char prefix[4] = {0};
	// GetTempFileNameA() uses up to the first three characters of the prefix
	// and windows filesystems are case-insensitive
	const char *base32set = "abcdefghijklmnopqrstuvwxyz012345";
	ev_uint16_t rnd;

	evutil_secure_rng_get_bytes(&rnd, sizeof(rnd));
	prefix[0] = base32set[(rnd      ) & 31];
	prefix[1] = base32set[(rnd >>  5) & 31];
	prefix[2] = base32set[(rnd >> 10) & 31];
	prefix[3] = '\0';

	printf("prefix=%s\n", prefix);
	return 0;
}
```

```
$ gcc -Wall -Wextra -o rndprefix rndprefix.c -levent_core
$ ./rndprefix 
prefix=cxl
$ ./rndprefix 
prefix=jun
$ ./rndprefix 
prefix=p0v
$ ./rndprefix 
prefix=zns
$ ./rndprefix 
prefix=1p2
$ ./rndprefix 
prefix=mxx
```

**Comment by ploxiln** [comment]
It looks like the windows 2019 builds (which actually use the tmpfile and AF_UNIX stuff) fail pretty hard, for reasons other than mbedtls, so this may have broken it ... a windows user could try to debug this I guess.

**Comment by davinci26** [comment]
Thanks @ploxiln for jumping into the issue!

**Comment by ploxiln** [comment]
(after rebasing on latest master, practically all windows tests pass, so that's nice)

**Pull request merged**
