### PR TITLE
be_pair: release shared lock with the latest of bufferevent_pair

### PR DESCRIPTION
**Pull request by azat**
Then next code sample will use free'd lock:
```
  evthread_use_pthreads();
  ...
  assert(!bufferevent_pair_new(base, BEV_OPT_THREADSAFE, pair));
  ...
  bufferevent_free(pair[1]); <-- free(lock)
  bufferevent_free(pair[0]); <-- acquire(lock) -- already free'd
```

While if you will reverse the order:
```
  bufferevent_free(pair[0]);
  bufferevent_free(pair[1]); <-- free(lock)
```

It is ok now, but I guess that it will be better to relax order of
freeing pairs.

**UPDATE: for error you must firstly free original owner -- i.e. `pair[0]` not `pair[1]`**

### CODE REVIEW

**Comment by nmathewson** [comment]
Could this get a test case?

**Comment by nmathewson** [comment]
Other than that, it looks fine to me.

**Comment by azat** [comment]
> Could this get a test case?

Sure, actually I'm working on this, but it is not so easy as it could
be (I'm trying to implement it without valgrind, since valgind didn't
used by libevent for such tests, but this is a separate topic).

**Comment by azat** [comment]
On Fri, Jan 23, 2015 at 02:53:07PM +0300, Azat Khuzhin wrote:
> > Could this get a test case?
> 
> Sure, actually I'm working on this, but it is not so easy as it could
> be (I'm trying to implement it without valgrind, since valgind didn't
> used by libevent for such tests, but this is a separate topic).

Hi Nick,

Could please look at the next branch:

git@github.com:azat/libevent.git be-pair-fix-freeing-shared-lock-v5

      be_pair: release shared lock with the latest of bufferevent_pair
      evthread: add evthread_get_{lock,condition}_callbacks() helpers
      evthread: evthreadimpl_disable_lock_debugging_() for libevent_global_shutdown()
      event_free_debug_globals_locks(): disable lock debugging
      be_pair/regress: cover use of shared lock (lock/unlock/free)

The first one is the initial patch, it has updated comments, so please don't
confuse it with existing one.
Other 4 commits -- for regression test.

Or by web:
https://github.com/azat/libevent/compare/be-pair-fix-freeing-shared-lock-v5?expand=1

If you want to, I could close this and open new pull request with v5
version.

Thanks,
Azat!

**Comment by nmathewson** [comment]
merged that; thanks!

**Pull request closed without merging**
