### PR TITLE
Release 2.1.12 stable pull

### PR DESCRIPTION
**Pull request by azat**
**This is PR for the 2.1.12 release.**

#### ABI compatibility:

Version | Date | Soname | ChangeLog | BackwardCompatibility | AddedSymbols | RemovedSymbols | HeadersDiff
-- | -- | -- | -- | -- | -- | -- | --
current | 2020-06-2822:14 | 2.1.7 | changelog | 100% | 2 new | 0 | 3
2.1.11 | 2019-08-01 | 2.1.7 | changelog | 78.43%changed SONAME | 0 | 0 | 6

##### AddedSymbols:

- evutil_inet_pton_scope

### CODE REVIEW

**Comment by azat** [comment]
> export test failures (@ygj6 can you take a look?)

@ygj6 can you take a look?

**Comment by ygj6** [comment]
>export test failures (@ygj6 can you take a look?)

Sorry for the delay.
By comparing the source code and test verification, it is found that the two commits are not merged in [azat:release-2.1.12-stable-pull](https://github.com/azat/libevent/tree/release-2.1.12-stable-pull).
https://github.com/libevent/libevent/commit/9adc9f149657212f65f05750b4f94ea3b1166aec
https://github.com/libevent/libevent/commit/ce8be2385b5fee16859a630fca0c98ad290c8e21
In addition, you need to adjust Libevent 2.2.0 to Libevent 2.1.0 in test-export/CMakeLists.txt.
I have verified on the [release-2.1.12](https://github.com/ygj6/libevent/tree/release-2.1.12) branch,Please check.
https://github.com/ygj6/libevent/commit/410552aca1a09f06072c4d38db7b3efb86d36495

**Comment by azat** [comment]
@ygj6 many thanks!

**Comment by azat** [comment]
> should cache key includes git ref?

No need to:

https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key

**Pull request merged**
