### PR TITLE
Use read/write instead of readv/writev for single buffer

### PR DESCRIPTION
**Pull request by panjf2000**
The `readv`/`writev` functions are designed for scattered I/O optimally,
their logic in the kernel is more sophisticated, compared to read/write,
which includes extra on-stack `iovec` in the kernel space, importing `iovec`
array from user space to kernel space, reading/writing with `iov_iter`, etc.
As a result, using `readv`/`writev` on single-segment `iovec` will fall into
the special branch in the kernel where it is imported as `ITER_UBUF` differed
from `ITER_IOVEC` for multiple-segments `iovec`.

Thus, it is just not worth calling `readv`/`writev` for single-segment `iovec`,
we should use `read`/`write` instead, to save it from going through the
sophisticated yet unnecessary kernel code path, circumvent a waste of
kernel on-stack memory, copying `iovec` between user space and kernel space, etc.

### CODE REVIEW

**Review by azat — COMMENTED** [review]
I'm OK with this change, but can you do some benchmarks to verify that there is some difference?

**Comment by panjf2000** [comment]
> I'm OK with this change, but can you do some benchmarks to verify that there is some difference?

Sorry for the delay, I was a bit busy just now and I'm just now getting around to writing a benchmark and replying to you, please check out [the benchmark code and result](https://gist.github.com/panjf2000/bd41b55f09ff1766c721505aaca50bfa).
@azat

**Comment by panjf2000** [comment]
Kindly ping @azat

**Review by azat — APPROVED** [review]
Thank you for the benchmark, indeed, looks useful!

**Pull request merged**
