### PR TITLE
Eliminate the redundant ev_uint64_t for eventfd

### PR DESCRIPTION
**Pull request by panjf2000**
Signed-off-by: Andy Pan <i@andypan.me>

### CODE REVIEW

**Comment by panjf2000** [comment]
Ping @azat

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
Interesting, why CI failed for mingw?

```
../evutil.c: In function 'evutil_set_tcp_keepalive':
../evutil.c:3147:54: error: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 3147 |         if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &on, sizeof(on)))
      |                                                      ^~~
      |                                                      |
      |                                                      int *
In file included from ../evutil.c:39:
D:/a/_temp/msys64/mingw64/include/winsock2.h:1035:88: note: expected 'const char *' but argument is of type 'int *'
 1035 |   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
      |                                                                            ~~~~~~~~~~~~^~~~~~
../evutil.c:3161:55: error: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 3161 |         if (setsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, &idle, sizeof(idle)))
      |                                                       ^~~~~
      |                                                       |
      |                                                       int *
D:/a/_temp/msys64/mingw64/include/winsock2.h:1035:88: note: expected 'const char *' but argument is of type 'int *'
 1035 |   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
      |                                                                            ~~~~~~~~~~~~^~~~~~
../evutil.c:3164:56: error: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 3164 |         if (setsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, &intvl, sizeof(intvl)))
      |                                                        ^~~~~~
      |                                                        |
      |                                                        int *
D:/a/_temp/msys64/mingw64/include/winsock2.h:1035:88: note: expected 'const char *' but argument is of type 'int *'
 1035 |   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
      |                                                                            ~~~~~~~~~~~~^~~~~~
../evutil.c:3168:54: error: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 3168 |         if (setsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, &cnt, sizeof(cnt)))
      |                                                      ^~~~
      |                                                      |
      |                                                      int *
```

**Comment by panjf2000** [comment]
No idea, these seem like recent failure of compiler errors which used to be compiler warns.

**Comment by panjf2000** [comment]
GCC version got changed on that runner?

**Comment by azat** [comment]
I haven't checked yet, maybe you can take a look?

**Comment by panjf2000** [comment]
I'll try to find out the root cause, and maybe open a PR explicitly casting the data pointer to the expected type to avoid this kind warnings/errors if I have to.

**Pull request merged**
