### PR TITLE
Add error-handling routine for arc4_seed()

### PR DESCRIPTION
**Pull request by sungjungk**
Motivation:
- There is no error-handling routine after calling 'arc4_seed()'

Modification:
- Correct the above issue

### CODE REVIEW

**Comment by NathanFrench** [comment]
Thank you.

**Comment by ploxiln** [comment]
it's pretty weird, but it looks like the `arc4_seeded_ok` check was equivalent

**Comment by NathanFrench** [comment]
Ok it seems as if this pull request has not been cleared, reverting.

**Comment by NathanFrench** [comment]
Sorry, my bad. In the future, I will not immediately merge these types of requests as they dirty our history.

**Comment by sungjungk** [comment]
In this case, it would be better to remove the following code:
```
if (!arc4_seeded_ok)
    return -1;
```
How about this?

**Comment by ploxiln** [comment]
It's not a big deal, this way is correct too ... just clarifying that I think it worked correctly before as well. Yes, I think we can remove that `arc4_seeded_ok` check in that function now.

**Comment by sungjungk** [comment]
I just did it.
Please check PR #771.

**Pull request merged**
