### PR TITLE
Adds configure check for midipix

### PR DESCRIPTION
**Pull request by Redfoxmoon3**
Adds configure check for midipix

### CODE REVIEW

**Comment by azat** [comment]
I don't use any *win* stuff, so googling for `ac_pe_target` doesn't show anything (except link to this patch and test for it in appveyor), so what this all about?
Should I set this variable myself? If so, maybe it will be better to detect it my (i.e. maybe it defines some macro?)?
In which env are you trying to build?

**Comment by Redfoxmoon3** [comment]
Currently it's only used by midipix, an alternative POSIX layer to cygwin, but it's a define for any system using PE executables - and therefore needing -no-undefined

**Comment by azat** [comment]
So you should set `ac_pe_target` manually, or I missing something?

Why not just write something like this to auto-detect this case (seems that midipix defines `__midipix__`) ?
```
dnl - check if the macro __midipix__ is defined on this compiler.
dnl - (this is how we check for a midipix version of GCC)
AC_MSG_CHECKING(for midipix)
AC_TRY_COMPILE(,
        [
#ifndef __midipix__
die horribly
#endif
        ],
        midipix=true; AC_MSG_RESULT(yes),
        midipix=false; AC_MSG_RESULT(no),
)
```

```
AM_CONDITIONAL(BUILD_WITH_NO_UNDEFINED, test x$bwin32 = xtrue || test x$cygwin = xtrue || test x$midipix = xtrue)
```

**Comment by Redfoxmoon3** [comment]
That works too, but midipix also sets __PE__ (specifically for stuff like this) which is generic

**Comment by azat** [comment]
Applied, thanks! (upstream commit is 94e5cc84)

**Comment by azat** [comment]
@Redfoxmoon3 can you add the same check into cmake rules?

**Comment by Redfoxmoon3** [comment]
I've no idea how to write cmake rules. sorry.

**Comment by azat** [comment]
Got it, will do myself, thanks anyway!

**Pull request closed without merging**
