### PR TITLE
cmake: Fix Android build.

### PR DESCRIPTION
**Pull request by rpavlik**
Android/Bionic C library needs no special flags to have threading support.
Found when trying to build with vcpkg.

### CODE REVIEW

**Comment by azat** [comment]
Thanks! Maybe you can write an instruction on how to build libevent on Android? (This will help with #1351)

**Comment by rpavlik** [comment]
I think the CI failure is spurious.

**Comment by rpavlik** [comment]
I just did `./vcpkg install libevent:x64-android` after setting ANDROID_NDK_HOME, like any other vcpkg package, once this patch was applied. 

Testing here on its own, looks like the following will build a simple version of the library:

```
cmake -G Ninja -S . -B build -DCMAKE_TOOLCHAIN_FILE=/home/ryan/Android/Sdk/ndk/23.2.8568313/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=26 -DEVENT__DISABLE_OPENSSL=ON -DEVENT__DISABLE_MBEDTLS=ON -DEVENT__DISABLE_TESTS=ON
```

**Comment by azat** [comment]
Thanks!

**Review by azat — APPROVED** [review]

**Review by azat — APPROVED** [review]

**Pull request merged**
