### PR TITLE
Return from 'event_del()' after the last event callback termination

### PR DESCRIPTION
**Pull request by jmillan**
Delete the event from the queue before blocking for the current
event callback termination.

Ensures that no callback is being executed when 'event_del()' returns,
hence making this function a secure mechanism to access data which is
handled in the event callack.

### CODE REVIEW

**Comment by jmillan** [comment]
Accommodation of #226 PR for master branch.

**Comment by azat** [comment]
Refs #225

**Comment by raphaelcoeffic** [comment]
@azat Hey! What is actually blocking here? Is there anything I can do? I'm working with @jmillan together, and was wondering lately why our patch did not get included upstream. We're using libevent 2.0.21 with this patch for quite some time now (well, 2 years) and have never seen any issue with it.

**Comment by azat** [comment]
Hi @raphaelcoeffic and @jmillan 

@raphaelcoeffic thanks for the reminder and many thanks to @jmillan for the patch and detailed description.

This tooks so much time because this behavior should be documented somewhere, and the best place for this is unit test. I added a regression (modified `del_wait`) test for this and applied patch! (sorry that this took so much time)

And yeah, this should be useful (since after `event_del()` one can think that event will not be triggered again).

Also I want to note that this patch landed into 2.2, can you try latest libevent for your project?

**Pull request closed without merging**
