### PR TITLE
do not build test programs by default

### PR DESCRIPTION
**Pull request by vapier**
The test binaries are used when you run `make check`, so change the code
so they're only built when you run that target.  It doesn't make sense
to always compile these when you run plain `make`.

### CODE REVIEW

**Comment by vapier** [comment]
you can still build specific tools if you want them like `make test/bench`.  maybe you could add an explicit target for building these like `make build_tests` ?  automake doesn't seem to produce a pseudo target to build all `$(check_PROGRAMS)` afaict.

`noinst` is intended to be used for build time tools or build-only libraries (like internal static libs).  it's not meant for building test programs that are only used by `make check` -- that's why `check_PROGRAMS` exists.

i guess it's less of an issue now that the `noinst_PROGRAMS` assignment is under the `BUILD_REGRESS` check.

**Comment by azat** [comment]
>you can still build specific tools if you want them like make test/bench. maybe you could add an explicit target for building these like make build_tests ?

I know, but this requires extra commands, since like I said I need to build the whole libevent and run only regress, hence I will need to run make twice which I can do but don't want to.

>noinst is intended to be used for build time tools or build-only libraries (like internal static libs). it's not meant for building test programs that are only used by make check -- that's why check_PROGRAMS exists.

Indeed, but can we eliminate second make for my use case? (I'm not the fan of autotools anymore)

Also has cmake rules, and this will introduce diff with it

**Comment by azat** [comment]
>i guess it's less of an issue now that the noinst_PROGRAMS assignment is under the BUILD_REGRESS check.

So are you still think that it is worth it?

**Comment by azat** [comment]
Closing this for now. @vapier if you still have strong feeling in that this should be fixed, please reopen.

**Pull request closed without merging**
