### PR TITLE
Add parameter length check

### PR DESCRIPTION
**Pull request by xiaoge1001**
Fix https://github.com/libevent/libevent/issues/1573

### CODE REVIEW

**Comment by liudongmiao** [comment]
I don't think `sizeof(*out)` is a good practice.

**Comment by xiaoge1001** [comment]
> I don't think `sizeof(*out)` is a good practice.

Why? I looked at the parameter description of this function, and it should be like this.

https://github.com/libevent/libevent/blob/master/include/event2/util.h#L673

**Comment by liudongmiao** [comment]
struct sockaddr: 16
struct sockaddr_in6: 28
struct sockaddr_in: 16
struct sockaddr_storage: 128

**Comment by liudongmiao** [comment]
> > I don't think `sizeof(*out)` is a good practice.
> 
> Why? I looked at the parameter description of this function, and it should be like this.
> 
> https://github.com/libevent/libevent/blob/master/include/event2/util.h#L673

`sizeof(*out)` means `sizeof(struct sockaddr)` is not large enough for ipv6.

**Comment by xiaoge1001** [comment]
> > > I don't think `sizeof(*out)` is a good practice.
> > 
> > 
> > Why? I looked at the parameter description of this function, and it should be like this.
> > https://github.com/libevent/libevent/blob/master/include/event2/util.h#L673
> 
> `sizeof(*out)` means `sizeof(struct sockaddr)` is not large enough for ipv6.

Actually, I've always wondered why out isn't declared as a struct sockaddr_storage pointer, but as a struct sockaddr?

**Comment by xiaoge1001** [comment]
> struct sockaddr: 16 struct sockaddr_in6: 28 struct sockaddr_in: 16 struct sockaddr_storage: 128

I think this check can be added.

**Comment by azat** [comment]
Sorry, but I don't think that it worth it

**Pull request closed without merging**
