### PR TITLE
Have evhttp_connection_cb_cleanup check if it should free the request.

### PR DESCRIPTION
**Pull request by pphaneuf**
This should help with #68, but I might have missed some cases, so your mileage may vary.

### CODE REVIEW

**Comment by pphaneuf** [comment]
One philosophical question I was thinking of: if you call the user's request callback with a NULL, should you free the ```evhttp_request```? When I noticed that this happened, I started passing myself the ```evhttp_request``` via the user pointer (using a struct)...

I think there's even some cases where the callback is not called at all, but the user might still have kept a list of the ```evhttp_request```s it created, and could double-free later on.

**Comment by ellzey** [comment]
referencing comment here: https://github.com/libevent/libevent/issues/68#issuecomment-109562948 too

**Comment by azat** [comment]
Fixed in 9b16d9b845f5f5bf7653fae4a1d9b0b0960c492d

**Comment by azat** [comment]
@pphaneuf if you call `evhttp_request_own()` libevent will free that request, even if it calls request callback with `NULL`

**Pull request closed without merging**
